// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginHistoryReq struct {
	StartTime string `form:"start_time,optional"`            // 开始时间，格式：2006-01-02 15:04:05，默认30天前
	EndTime   string `form:"end_time,optional"`              // 结束时间，格式：2006-01-02 15:04:05，默认当前时间
	Offset    int    `form:"offset,default=1,range=[1:]"`    // 页码，默认1
	Limit     int    `form:"limit,default=20,range=[1:100]"` // 每页大小，默认20，最大100
}

type LoginHistoryResp struct {
	Entries    []LoginHistoryItem `json:"entries"`     // 登录记录列表
	TotalCount int64              `json:"total_count"` // 总记录数
}

type LoginReq struct {
	Phone    string `json:"phone" validate:"required,len=11,regexp=^1[3-9]\\d{9}$"` // 手机号
	Password string `json:"password" validate:"required"`                           // 密码
}

type LoginResp struct {
	AccessToken  string   `json:"access_token"`  // 访问令牌，2小时有效
	RefreshToken string   `json:"refresh_token"` // 刷新令牌，7天有效
	UserInfo     UserInfo `json:"user_info"`     // 用户信息
}

type LogoutReq struct {
}

type LogoutResp struct {
	Success bool `json:"success"` // 是否成功
}

type RefreshReq struct {
	RefreshToken string `json:"refresh_token" validate:"required"` // 刷新令牌
}

type RefreshResp struct {
	AccessToken string `json:"access_token"` // 新的访问令牌，2小时有效
}

type RegisterReq struct {
	Phone    string `json:"phone" validate:"required,len=11,regexp=^1[3-9]\\d{9}$"`                                                           // 手机号
	Code     string `json:"code" validate:"required,len=6,regexp=^\\d{6}$"`                                                                   // 验证码，6位数字
	Password string `json:"password" validate:"required,min=8,regexp=^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$"` // 密码：至少8位，包含大小写字母、数字和特殊字符
}

type RegisterResp struct {
	UserId int64  `json:"user_id"` // 用户ID
	Phone  string `json:"phone"`   // 手机号
}

type ResetPasswordReq struct {
	Phone    string `json:"phone" validate:"required,len=11,regexp=^1[3-9]\\d{9}$"`                                                           // 手机号
	Code     string `json:"code" validate:"required,len=6,regexp=^\\d{6}$"`                                                                   // 验证码
	Password string `json:"password" validate:"required,min=8,regexp=^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$"` // 新密码
}

type ResetPasswordResp struct {
	Success bool `json:"success"` // 是否成功
}

type SendCodeReq struct {
	Phone string `json:"phone" validate:"required,len=11,regexp=^1[3-9]\\d{9}$"` // 手机号，11位数字，1开头
	Type  string `json:"type" validate:"required,oneof=register reset"`          // 类型：register=注册，reset=重置密码
}

type SendCodeResp struct {
	Success bool `json:"success"` // 是否发送成功
}

type SendResetCodeReq struct {
	Phone string `json:"phone" validate:"required,len=11,regexp=^1[3-9]\\d{9}$"` // 手机号
}

type SendResetCodeResp struct {
	Success bool `json:"success"` // 是否发送成功
}

type UpdatePasswordReq struct {
	OldPassword string `json:"old_password" validate:"required"`                                                                                     // 旧密码
	NewPassword string `json:"new_password" validate:"required,min=8,regexp=^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$"` // 新密码
}

type UpdatePasswordResp struct {
	Success bool `json:"success"` // 是否成功
}
