// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type EmptyResp struct {
}

type IdReq struct {
	Id int64 `path:"id"`
}

type IdsReq struct {
	Ids []int64 `json:"ids"`
}

type KeywordInfo struct {
	Keyword string `form:"keyword,optional"` // 关键字查询
}

type LoginHistoryItem struct {
	Id          int64  `json:"id"`           // 记录ID
	LoginTime   string `json:"login_time"`   // 登录时间
	IpAddress   string `json:"ip_address"`   // IP地址
	UserAgent   string `json:"user_agent"`   // 设备信息
	LoginResult int    `json:"login_result"` // 登录结果：1=成功，0=失败
	FailReason  string `json:"fail_reason"`  // 失败原因（仅失败时有值）
}

type PageBaseInfo struct {
	Offset int `form:"offset,default=1,range=[1:]"`     // 页码，默认1
	Limit  int `form:"limit,default=10,range=[0:2000]"` // 每页大小，默认10，0表示不分页
}

type PageInfo struct {
	PageBaseInfo
	Direction string `form:"direction,default=desc,options=asc|desc"`               // 排序方向：asc 正序，desc 倒序
	Sort      string `form:"sort,default=created_at,options=created_at|updated_at"` // 排序字段
}

type PageInfoWithKeyword struct {
	PageInfo
	KeywordInfo
}

type PageResp struct {
	Entries    interface{} `json:"entries"`     // 数据列表
	TotalCount int64       `json:"total_count"` // 总记录数
}

type UserInfo struct {
	Id       int64  `json:"id"`       // 用户ID
	Phone    string `json:"phone"`    // 手机号
	Nickname string `json:"nickname"` // 昵称
}
