// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	auth "github.com/jinguoxing/idrm-sdd-demo/api/internal/handler/auth"
	"github.com/jinguoxing/idrm-sdd-demo/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				// 查询登录历史
				Method:  http.MethodGet,
				Path:    "/login-history",
				Handler: auth.LoginHistoryHandler(serverCtx),
			},
			{
				// 用户登出
				Method:  http.MethodPost,
				Path:    "/logout",
				Handler: auth.LogoutHandler(serverCtx),
			},
			{
				// 修改密码
				Method:  http.MethodPut,
				Path:    "/password",
				Handler: auth.UpdatePasswordHandler(serverCtx),
			},
			{
				// 刷新访问令牌
				Method:  http.MethodPost,
				Path:    "/refresh",
				Handler: auth.RefreshHandler(serverCtx),
			},
			{
				// 用户注册
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
			{
				// 重置密码
				Method:  http.MethodPost,
				Path:    "/reset-password",
				Handler: auth.ResetPasswordHandler(serverCtx),
			},
			{
				// 发送注册验证码
				Method:  http.MethodPost,
				Path:    "/send-code",
				Handler: auth.SendCodeHandler(serverCtx),
			},
			{
				// 发送重置密码验证码
				Method:  http.MethodPost,
				Path:    "/send-reset-code",
				Handler: auth.SendResetCodeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/auth"),
	)
}
